# Generated by Django 5.2.3 on 2025-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Seller', models.CharField(max_length=255)),
                ('Rating', models.FloatField()),
                ('Feedbacks', models.IntegerField()),
                ('Sale_Price', models.FloatField()),
                ('Price', models.FloatField()),
                ('Article', models.CharField(max_length=20)),
            ],
        ),
    ]
